ALTER TABLE accounts ADD COLUMN force_hydrate BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE accounts ADD COLUMN total_collabs INT4 NOT NULL DEFAULT 0;
ALTER TABLE accounts ADD COLUMN total_collab_rewards VARCHAR NOT NULL DEFAULT '0x0';
ALTER TABLE accounts ADD COLUMN total_campaigns INT4 NOT NULL DEFAULT 0;
ALTER TABLE accounts ADD COLUMN total_collabs_received INT4 NOT NULL DEFAULT 0;
ALTER TABLE accounts ADD COLUMN total_spent VARCHAR NOT NULL DEFAULT '0x0';
ALTER TABLE accounts ADD COLUMN unclaimed_asami_balance VARCHAR NOT NULL DEFAULT '0x0';
ALTER TABLE accounts ADD COLUMN unclaimed_doc_balance VARCHAR NOT NULL DEFAULT '0x0';
ALTER TABLE accounts ADD COLUMN asami_balance VARCHAR NOT NULL DEFAULT '0x0';
ALTER TABLE accounts ADD COLUMN doc_balance VARCHAR NOT NULL DEFAULT '0x0';
ALTER TABLE accounts ADD COLUMN rbtc_balance VARCHAR NOT NULL DEFAULT '0x0';
ALTER TABLE accounts ADD COLUMN last_on_chain_sync TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE handles ADD COLUMN force_hydrate BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE handles ADD COLUMN total_collabs INT4 NOT NULL DEFAULT 0;
ALTER TABLE handles ADD COLUMN total_collab_rewards VARCHAR NOT NULL DEFAULT '0x0';

ALTER TABLE campaigns ADD COLUMN force_hydrate BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE campaigns ADD COLUMN total_collabs INT4 NOT NULL DEFAULT 0;
ALTER TABLE campaigns ADD COLUMN total_spent VARCHAR NOT NULL DEFAULT '0x0'; 
ALTER TABLE campaigns ADD COLUMN total_budget VARCHAR NOT NULL DEFAULT '0x0';

UPDATE accounts SET force_hydrate = TRUE;
UPDATE handles SET force_hydrate = TRUE;
UPDATE campaigns SET force_hydrate = TRUE;
