version: 2.1

orbs:
  rust: circleci/rust@1.6.0
  browser-tools: circleci/browser-tools@1.4.6

workflows:
  version: 2
  full_test_suite:  # This is the name of the workflow, feel free to change it to better match your workflow.
    jobs:
      - models_and_api
      - integration_tests

jobs:
  integration_tests:
    docker:
      - image: constata/asami-test:latest
      - image: cimg/postgres:13.4
        environment:
          POSTGRES_USER: asami
          POSTGRES_PASSWORD: password
          POSTGRES_DB: asami_development
    resource_class: xlarge
    steps:
      - checkout
      - browser-tools/install-chrome:
        chrome-version: "126.0.6478.61"
      - browser-tools/install-chromedriver:
        chrome-version: "126.0.6478.61"
      - run:
          name: Creating config
          command: cp api/Rocket.toml.sample api/Rocket.toml
      - run:
          name: Wait for postgres
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Wait for schema creation
          command: cd api && until sqlx database setup; do echo "Creating DB"; sleep 1; done;
      - run:
          name: Make artifacts dir
          command: mkdir -p target/artifacts

      - run:
          name: Run tests
          command: integration_tests/run webapp

      - store_artifacts:
          path: target/artifacts

  models_and_api:
    docker:
      - image: constata/asami-test:latest
      - image: cimg/postgres:13.4
        environment:
          POSTGRES_USER: asami
          POSTGRES_PASSWORD: password
          POSTGRES_DB: asami_development
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Creating config
          command: cp api/Rocket.toml.sample api/Rocket.toml
      - run:
          name: Wait for postgres
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Wait for schema creation
          command: cd api && until sqlx database setup; do echo "Creating DB"; sleep 1; done;
      - run:
          name: Make artifacts dir
          command: mkdir -p target/artifacts

      - run:
          name: Run tests
          command: cargo test --workspace --exclude webapp --no-fail-fast -- --test-threads 1

      - store_artifacts:
          path: target/artifacts
