[global]
pwa_host="http://127.0.0.1:5173"
url = "http://localhost:8000"
address="0.0.0.0"
limits = { json = "50MB", graphql = "50MB" }
database_uri = "postgres://asami:password@localhost/asami_development"
recaptcha_threshold=0.0
sendgrid_api_key="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"

[global.x]
client_id="ZDJUaWk3OVpEU3JTaW12VFFBQmg6MTpjaQ"
client_secret="lydyeW0Uc-QBnOcq9xgTqJl2s61XoceFZQ36cOcNKZn6hFk_jm"
redirect_uri = "http://127.0.0.1:8000/x_login"
bearer_token = "AAAAAAAAAAAAAAAAAAAAAOVCqQEAAAAAQsvtZ39Y3s74VfESFkBhTkLiuCA%3DKqoV27b4q6yW3oDVSDHZaWbAnlajtRmFLzA9WVRUnnw5OlA2N9"
asami_user_id = 1688942981573685248
crawl_cooldown_minutes = 10

[global.instagram]
client_id = "3539139656337829"
client_secret = "393ab13f702c36974c7a4facb1426b94"
redirect_uri = "https://127.0.0.1:8000/instagram_login"
crawl_cooldown_minutes = 10
apify_key = "apify_api_2D4k43ka1q3Gl5pVp4rGh22ZebDOhj4cl0M3"
verification_image_url = "https://asami.ams3.digitaloceanspaces.com/asami_instagram_white.png"
verification_caption = "I've joined asami.club, starting today some of mi posts will be sponsored. You can join too at https://asami.club"
verification_posts_count = 5

[global.recaptcha.v3]
html_key="6LeEosgoAAAAAEvZM2fmutlMhYwFMtpFwo_3BIDX"
secret_key="6LeEosgoAAAAAEmwBs9iLiRb_k-fJhlTq6OmOrjd"

[global.rsk]
chain_id=31337
start_sync_from_block=0
wallet_mnemonic="work man father plunge mystery proud hollow address reunion sauce theory bonus"
admin_address="0xed4e67213c7a375af60893fe8e0852d0f7040913"
legacy_contract_address="unknown"
asami_contract_address="unknown"
doc_contract_address="unknown"
rpc_url="http://127.0.0.1:8545"
reorg_protection_padding="0x0000"
blockchain_sync_cooldown=0
gasless_rbtc_per_user="0x574FBDE6000" # 6e12 This is the contract's default so we're using it.
gasless_fee="0xDE0B6B3A7640000" # 1 DOC, this is a contract default.
admin_claim_trigger="0x2A5A058FC295EC000000" # When the admin has this many asami tokens, it will claim.
