#!/bin/bash
pgrep -f "integration_tests/target/debug/deps" | xargs -r kill -9
pgrep -f "bin/ganache" | xargs -r kill -9
cargo test -j 4 --color always --test $1 $2 -- --test-threads 1 --nocapture 2>&1 | less -R
