#!/bin/bash 

export ADMIN_ADDRESS=0xed4e67213c7a375af60893fe8e0852d0f7040913
export MEMBER_ADDRESS=0x68aC79AE5D9C9eaf6c783836C35bbcbaCAe7C771
rm -rf build scripts/ganache.log
truffle compile &&
truffle compile test/MockDoc.sol &&
INSTANCE=$(ganache -D --logging.file=scripts/ganache.log) &&
truffle migrate --network local &&
truffle exec scripts/local_blockchain_state.js --network local  &&
echo "All set, starting log output" &&
echo stop with ganache instances stop $INSTANCE &&
echo see log with tail -f -n 100 scripts/ganache.log
