#!/bin/bash
set -a
[ -f .env_local ] && . .env_local
set +a

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
"$SCRIPT_DIR/run-local-db"

pgrep -f "hardhat node" | xargs -r kill -9
pgrep -f "integration_tests/target/debug/deps" | xargs -r kill -9
RUST_BACKTRACE=1 cargo run --bin run-dev
