[global]
pwa_host="http://127.0.0.1:5173"
url = "http://localhost:8000"
address="0.0.0.0"
limits = { json = "50MB", graphql = "50MB" }
database_uri = "postgres://asami:password@localhost/asami_development"
recaptcha_threshold=0.0
wallet_mnemonic="work man father plunge mystery proud hollow address reunion sauce theory bonus"
admin_address="0xed4e67213c7a375af60893fe8e0852d0f7040913"
contract_address="unknown"

[global.x]
client_id="ZDJUaWk3OVpEU3JTaW12VFFBQmg6MTpjaQ"
client_secret="lydyeW0Uc-QBnOcq9xgTqJl2s61XoceFZQ36cOcNKZn6hFk_jm"
redirect_uri = "http://127.0.0.1:8000/x_login"
bearer_token = "AAAAAAAAAAAAAAAAAAAAAOVCqQEAAAAAVggWXDpb2XV820P8Zjhy%2BTXR1cc%3DSVEKs2Cx77t2SLB7lRqtqWIoSFra4YxFh1SsW1x2ph96nG2W0L"
asami_user_id = 1688942981573685248
#asami_user_id = 179383862

[global.instagram]
client_id = "3539139656337829"
client_secret = "8f1aac2f280a3f9c3db27355138ff589"
redirect_uri = "https://127.0.0.1:8000/instagram_login"

[global.recaptcha.v3]
html_key="6LcMyXYoAAAAABLRzxeVZ1nae06LVvyv8l3O0LSz"
secret_key="6LcMyXYoAAAAAIW4XM1kpyZzLT2XMhWAIY5fKMlt"

[global.rsk]
chain_id=31
