name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: 1
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      ROCKET_RECAPTCHA: ${{ secrets.ROCKET_RECAPTCHA }}

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: asami
          POSTGRES_PASSWORD: password
          POSTGRES_DB: asami_development
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U asami"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.81.0
          target: x86_64-unknown-linux-gnu
          components: rustfmt, clippy
          override: true

      - name: Install Node and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: pwa/yarn.lock

      - name: Install frontend deps
        working-directory: ./pwa
        run: yarn install

      - name: Start Hardhat node
        run: |
          nohup npx hardhat node > hardhat.log 2>&1 &
          sleep 5

      - name: Install sqlx-cli
        run: cargo install sqlx-cli --no-default-features --features postgres

      - name: Prepare database
        run: |
          sudo apt-get install -y libpq-dev
          cd api
          sqlx database reset -y

      - name: Run cargo fmt
        run: cargo fmt -- --check

      - name: Run cargo clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: Run tests
        run: |
          cd integration_tests
          ./run webapp adds_tokens_to_wallet

